# Generated by Django 5.2.4 on 2025-09-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
        migrations.CreateModel(
            name='MoviesWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='whatched/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_entries', to='home_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='UnseenMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='unseen/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unseen_entries', to='home_app.movie')),
            ],
        ),
    ]
