# Generated by Django 5.2.4 on 2025-09-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
