# Generated by Django 5.2.4 on 2025-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieswatched',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unseenmovies',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
